# Generated by Django 6.0.4 on 2026-04-19 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('home_description', models.TextField(blank=True, verbose_name='Описание для главной')),
                ('page_title', models.CharField(blank=True, max_length=180, verbose_name='Заголовок страницы')),
                ('page_lead', models.TextField(blank=True, verbose_name='Подзаголовок страницы')),
                ('accent', models.CharField(blank=True, max_length=180, verbose_name='Акцентная строка')),
                ('filters_text', models.CharField(blank=True, help_text='Например: Все, Монобукеты, Сборные букеты, Композиции', max_length=255, verbose_name='Фильтры через запятую')),
                ('static_image', models.CharField(blank=True, help_text='Например: images/products/flowers.svg', max_length=255, verbose_name='Путь к статичному изображению')),
                ('image', models.FileField(blank=True, upload_to='categories/', verbose_name='Изображение категории')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.CharField(max_length=80, verbose_name='Цена')),
                ('tag', models.CharField(blank=True, max_length=80, verbose_name='Метка')),
                ('static_image', models.CharField(blank=True, help_text='Например: images/products/card-bouquet.svg', max_length=255, verbose_name='Путь к статичному изображению')),
                ('image', models.FileField(blank=True, upload_to='products/', verbose_name='Изображение товара')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать в хитах на главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Карточки товаров',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
