# Generated by Django 6.0.4 on 2026-04-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, verbose_name='Название изображения')),
                ('static_image', models.CharField(blank=True, help_text='Например: images/products/card-bouquet.svg', max_length=255, verbose_name='Путь к статичному изображению')),
                ('image', models.FileField(blank=True, upload_to='products/gallery/', verbose_name='Файл изображения')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
