# Generated by Django 6.0.4 on 2026-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crop_horizontal',
            field=models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('right', 'Справа')], default='center', max_length=10, verbose_name='Обрезка по горизонтали'),
        ),
        migrations.AddField(
            model_name='product',
            name='crop_vertical',
            field=models.CharField(choices=[('top', 'Сверху'), ('center', 'По центру'), ('bottom', 'Снизу')], default='center', max_length=10, verbose_name='Обрезка по вертикали'),
        ),
    ]
