# Generated by Django 6.0.4 on 2026-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_crop_horizontal_product_crop_vertical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='crop_horizontal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='crop_vertical',
        ),
        migrations.AddField(
            model_name='product',
            name='crop_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Кадрирование X'),
        ),
        migrations.AddField(
            model_name='product',
            name='crop_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Кадрирование Y'),
        ),
    ]
