# Generated by Django 6.0.4 on 2026-04-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_crop_horizontal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crop_scale',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Масштаб кадра'),
        ),
    ]
