# Generated by Django 6.0.4 on 2026-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_crop_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='static_image',
            field=models.CharField(blank=True, default='images/products/card-bouquet.svg', help_text='Например: images/products/card-bouquet.svg', max_length=255, verbose_name='Путь к статичному изображению'),
        ),
    ]
