# Generated by Django 6.0.4 on 2026-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_static_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, upload_to='products/videos/', verbose_name='Видео товара'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_scale',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Масштаб кадра'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Кадрирование X'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Кадрирование Y'),
        ),
    ]
