# Generated by Django 6.0.4 on 2026-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, upload_to='products/videos/', verbose_name='Видео товара'),
        ),
    ]
