# Generated by Django 6.0.4 on 2026-04-19 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, verbose_name='Название видео')),
                ('video', models.FileField(upload_to='products/videos/', verbose_name='Видео')),
                ('is_muted', models.BooleanField(default=True, verbose_name='Отключить звук')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_videos', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Видео товара',
                'verbose_name_plural': 'Видео товара',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
