# Generated by Django 6.0.4 on 2026-04-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
