# Generated by Django 6.0.4 on 2026-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='crop_scale',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Масштаб кадра'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='crop_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Кадрирование X'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='crop_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Кадрирование Y'),
        ),
    ]
