# Generated by Django 6.0.4 on 2026-04-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_product_description',
            field=models.TextField(blank=True, help_text='Показывается на странице товара, если у конкретной карточки описание не заполнено.', verbose_name='Описание товара по умолчанию'),
        ),
    ]
