# Generated by Django 6.0.4 on 2026-04-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_category_default_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategories_text',
            field=models.CharField(blank=True, help_text='Например: День рождения, Выписка, Свадьба. Если поле пустое, товары показываются сразу.', max_length=500, verbose_name='Подкатегории через запятую'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Выбирается из списка подкатегорий выбранной категории, если они указаны.', max_length=120, verbose_name='Подкатегория'),
        ),
    ]
